
spring:
  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop