
logging:
  level:
    org.springframework: INFO

server:
  port: 8080

spring:

  cache:
    jcache:
      config: classpath:ehcache.xml

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:postgresql://${SAFECHAT_DB_ADDRESS}/safechat-db
    username: ${SAFECHAT_DB_USERNAME}
    password: ${SAFECHAT_DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

